// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2QM-M5geG1VNn0oPqRE89ecP3RMSFCDw',
    appId: '1:1012169548117:web:6be4f7c4cfb7ee9599cfdc',
    messagingSenderId: '1012169548117',
    projectId: 'mastergig-db',
    authDomain: 'mastergig-db.firebaseapp.com',
    storageBucket: 'mastergig-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWI8g95nWmio6y5hWznRdkxLvBEZhmso0',
    appId: '1:1012169548117:android:4fe1054121a8f51f99cfdc',
    messagingSenderId: '1012169548117',
    projectId: 'mastergig-db',
    storageBucket: 'mastergig-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs7Ke9IWhN8t0O75pMgpxOAs89auGXsWw',
    appId: '1:1012169548117:ios:bb2a47ab4e62abf599cfdc',
    messagingSenderId: '1012169548117',
    projectId: 'mastergig-db',
    storageBucket: 'mastergig-db.firebasestorage.app',
    iosBundleId: 'com.example.mastergigApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs7Ke9IWhN8t0O75pMgpxOAs89auGXsWw',
    appId: '1:1012169548117:ios:bb2a47ab4e62abf599cfdc',
    messagingSenderId: '1012169548117',
    projectId: 'mastergig-db',
    storageBucket: 'mastergig-db.firebasestorage.app',
    iosBundleId: 'com.example.mastergigApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2QM-M5geG1VNn0oPqRE89ecP3RMSFCDw',
    appId: '1:1012169548117:web:b0edd8058fcbc70999cfdc',
    messagingSenderId: '1012169548117',
    projectId: 'mastergig-db',
    authDomain: 'mastergig-db.firebaseapp.com',
    storageBucket: 'mastergig-db.firebasestorage.app',
  );

}